//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductShop.Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryProduct
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdCountry { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Product Product { get; set; }
    }
}
