//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductShop.Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int Id { get; set; }
        public int IdProducts { get; set; }
        public decimal Count { get; set; }
        public decimal Cost { get; set; }
        public int IdProvider { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
